### ISSUE TITLE
运行报错，咋回事？

### ISSUE THREAD

**Issue by luzwales** [hzy-6/hzy-admin#3]
Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger<HZY.Framework.Repos
itory.EntityFramework.Repositories.Impl.UnitOfWorkImpl<HZY.Repository.Admin.AdminDbContext>>'. This is often because no database provider has been c
onfigured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the appl
ication service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger<HZY.Framework.Repository.EntityFramework.
Repositories.Impl.UnitOfWorkImpl<HZY.Repository.Admin.AdminDbContext>>'. This is often because no database provider has been configured for this DbC
ontext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provid
er. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService(IInfrastructure`1 accessor, Type serviceType)       
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at HZY.Framework.Repository.EntityFramework.Repositories.Impl.UnitOfWorkImpl`1.TrySavingAgainAsync(Func`1 saveAction)
   at HZY.Api.Admin.ApplicationServices.Core.Quartz.Impl.TaskService.RunByIdAsync(List`1 quartzJobTask)

**Comment by hzy-6** [comment]
gitee 下载最新代码
